root: true
env:
  browser: true
globals:
  $: true
  window: true
  require: true
rules:
  indent:
    - 1
    - 2
  quotes:
    - 1
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 1
    - always
  no-undef:
    - 2
  space-before-function-paren:
    - 0
  array-bracket-spacing:
    - 0
  one-var:
    - 2
    - always
  prefer-const:
    - 0
  comma-dangle:
    - 2
    - only-multiline
